# Generated by Django 2.2 on 2019-04-13 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category'},
        ),
        migrations.AlterField(
            model_name='product',
            name='pricing_tiers_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.PriceVariable', verbose_name='Pricing variable'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pricing_timeframe',
            field=models.CharField(blank=True, choices=[('monthly', 'monthly'), ('yearly', 'yearly'), ('lifetime', 'one-off')], max_length=190, null=True, verbose_name='Pricing timeframe'),
        ),
    ]
