# Generated by Django 2.2 on 2019-04-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190413_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='front_page_intro',
            field=models.TextField(default="Welcome to the pretix Marketplace! If you're hosting pretix yourself, this is the place where you can find plugins to extend your installation. If you use pretix through our pretix Hosted offering, you do not need this page, most useful plugins are already installed for you."),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='site_name',
            field=models.CharField(default='pretix Marketplace', max_length=255),
        ),
    ]
