# Generated by Django 2.2 on 2019-04-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190413_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_column_1',
            field=models.TextField(default='<h5>About</h5><ul class="list-unstyled text-small"><li><a class="text-muted" href="https://pretix.eu">pretix.eu</a></li></ul>'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_column_2',
            field=models.TextField(default='<h5>Tech</h5><ul class="list-unstyled text-small"><li><a class="text-muted" href="https://docs.pretix.eu">Docs</a></li></ul>'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_column_3',
            field=models.TextField(default='<h5>Legal</h5><ul class="list-unstyled text-small"><li><a class="text-muted" href="https://pretix.eu/about/en/imprint">Imprint</a></li><li><a class="text-muted" href="https://pretix.eu/about/en/privacy">Privacy</a></li></ul>'),
        ),
    ]
