# Generated by Django 2.2 on 2019-04-13 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190413_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.PROTECT, to='core.Vendor', verbose_name='Product vendor'),
        ),
    ]
