# Generated by Django 2.2 on 2019-04-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_siteconfiguration_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pypi_name',
            field=models.CharField(blank=True, max_length=190),
        ),
    ]
