# Generated by Django 2.2 on 2019-04-13 21:54

from django.db import migrations, models
import django.db.models.deletion
import plum.core.models.product


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_pypi_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-certified', 'name'), 'verbose_name': 'Product'},
        ),
        migrations.AlterModelOptions(
            name='productpricetier',
            options={'ordering': ('up_to_value',)},
        ),
        migrations.AlterModelOptions(
            name='productversion',
            options={'ordering': ('-release_date',)},
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='doc_installation',
            field=models.URLField(default='https://docs.pretix.eu/en/latest/admin/installation/index.html'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='post_install_commands',
            field=models.TextField(default='(venv)$ python -m pretix migrate(venv)$ python -m pretix rebuild# systemctl restart pretix-web pretix-worker'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='pre_install_commands',
            field=models.TextField(default='$ source /var/pretix/venv/bin/activate'),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='deliverable_file',
            field=models.FileField(blank=True, null=True, upload_to=plum.core.models.product.deliverable_filename),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='max_platform_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_upto', to='core.PlatformVersion', verbose_name='Maximum platform version'),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='min_platform_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_from', to='core.PlatformVersion', verbose_name='Minimum platform version'),
        ),
    ]
