# Generated by Django 2.2 on 2019-04-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190413_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='post_install_commands',
            field=models.TextField(default='(venv)$ python -m pretix migrate\n(venv)$ python -m pretix rebuild\n# systemctl restart pretix-web pretix-worker'),
        ),
    ]
