# Generated by Django 2.2 on 2019-04-13 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import plum.core.models.account


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190414_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=190, verbose_name='Name')),
                ('external_crm_id', models.CharField(blank=True, max_length=190)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='productpricetier',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('is_evaluation', models.BooleanField(default=False)),
                ('auth_token', models.CharField(default=plum.core.models.account.gen_auth_token, max_length=190)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='server', to='core.Account')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='core.Account')),
                ('pricing_tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='core.ProductPriceTier')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='core.Product')),
                ('servers', models.ManyToManyField(to='core.Server')),
            ],
        ),
    ]
