# Generated by Django 2.2 on 2019-04-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190414_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='productversion',
            name='deliverable_file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
