# Generated by Django 2.2 on 2019-04-14 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190414_2122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='license',
            options={'ordering': ('-end_date', '-start_date')},
        ),
        migrations.AddField(
            model_name='vendor',
            name='users',
            field=models.ManyToManyField(related_name='vendors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='server',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servers', to='core.Account'),
        ),
        migrations.AlterField(
            model_name='server',
            name='url',
            field=models.URLField(help_text='The base URL the platform runs at', verbose_name='URL'),
        ),
    ]
