# Generated by Django 2.2 on 2019-04-14 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20190414_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='buyer_contact',
            field=models.EmailField(default='support@pretix.eu', max_length=254),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='vendor_contact',
            field=models.EmailField(default='marketplace@pretix.eu', max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.Category', verbose_name='Product category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_method',
            field=models.CharField(choices=[('pypi', 'PyPI'), ('pip', 'Local python package index')], max_length=190, verbose_name='Delivery method'),
        ),
        migrations.AlterField(
            model_name='product',
            name='github_url',
            field=models.URLField(blank=True, verbose_name='GitHub URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='package_name',
            field=models.CharField(help_text='Should be a valid Python package name. For free packages, this is the name the package should be on on PyPI.', max_length=190, null=True, unique=True, verbose_name='Package name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stability',
            field=models.CharField(choices=[('alpha', 'alpha'), ('beta', 'beta'), ('stable', 'stable')], max_length=190, verbose_name='Stability'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.Vendor', verbose_name='Product vendor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='website_url',
            field=models.URLField(blank=True, verbose_name='Website URL'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='support_contact_email',
            field=models.EmailField(max_length=254, verbose_name='Support email address'),
        ),
    ]
