# Generated by Django 2.2.7 on 2019-11-12 21:25

from django.db import migrations, models
import plum.core.models.product


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20190415_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='upload_key',
            field=models.CharField(default=plum.core.models.product.gen_upload_key, max_length=64),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_method',
            field=models.CharField(choices=[('pypi', 'PyPI'), ('pip', 'Local python package index'), ('bundled', 'Bundled')], max_length=190, verbose_name='Delivery method'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stability',
            field=models.CharField(choices=[('alpha', 'alpha'), ('beta', 'beta'), ('stable', 'stable'), ('discontinued', 'discontinued')], max_length=190, verbose_name='Stability'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='support_contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Support email address'),
        ),
    ]
