# Generated by Django 3.2.11 on 2022-01-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20220107_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='android_client_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='android_package_name',
            field=models.CharField(blank=True, max_length=190, null=True, unique=True),
        ),
    ]
