# Generated by Django 3.2.11 on 2022-01-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20220108_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='android_is_on_gplay',
            field=models.BooleanField(default=False),
        ),
    ]
