# Generated by Django 3.2.11 on 2022-05-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_product_android_is_on_gplay"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="unlisted",
            field=models.BooleanField(default=False, verbose_name="Unlisted"),
        ),
    ]
