# Generated by Django 4.2.13 on 2024-06-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_product_unlisted"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AddField(
            model_name="product",
            name="pricing_url",
            field=models.URLField(blank=True, verbose_name="Pricing URL"),
        ),
    ]
