# Generated by Django 4.2.19 on 2025-02-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_alter_user_managers_product_pricing_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="productversion",
            name="allow_suggest",
            field=models.BooleanField(
                default=True, verbose_name="Allow using as suggested version"
            ),
        ),
    ]
